name: Kernel Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip flex bison libncurses-dev gawk libiberty-dev autoconf kmod bc build-essential gcc libc6 curl libstdc++6 git wget libssl-dev cpio p7zip-full

    - name: Clone toolchain repositories
      run: |
        git clone https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b --depth=1
        git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-10.0.0_r47 --depth=1
        git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-10.0.0_r47 --depth=1

    - name: Set up environment
      run: |
        CLANG=$PWD/android_prebuilts_clang_kernel_linux-x86_clang-r416183b/bin
        GCC64=$PWD/aarch64-linux-android-4.9/bin
        GCC32=$PWD/arm-linux-androideabi-4.9/bin
        export PATH=$CLANG:$GCC64:$GCC32:$PATH
        export args="-j$(nproc --all) ARCH=arm64 SUBARCH=arm64 O=$PWD/out CC=clang CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- LLVM=1"

    - name: Build kernel
      run: |
        cd sirius_Kernel
        make $args sirius_zhong_defconfig
        make $args
