name: Build KernelSU

on:
  workflow_dispatch:

jobs:
  KSUForSirius:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y zip flex bison libncurses-dev gawk  libiberty-dev autoconf kmod bc build-essential gcc libc6 curl libstdc++6 git wget libssl-dev cpio p7zip-full
          sudo apt clean
          
      - name: Cloning Sources and Toolchain
        run: |
          git clone https://github.com/liqideqq/Xiaomi_Kernel_Sirius --depth=1 -b main --recurse-submodules android_kernel_xiaomi_sdm710_LineageOS
 
      - name: Compiling Kernel(LineageOS)
        run: |
          CLANG=~/clang/bin
          GCC32=~/arm-linux-androideabi-4.9/bin
          GCC64=~/aarch64-linux-android-4.9/bin
          PATH=$CLANG:$GCC64:$GCC32:$PATH
          export PATH
          export ARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu
          export CROSS_COMPILE=aarch64-linux-android-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-
          output_dir=out
          pushd android_kernel_xiaomi_sdm710_LineageOS
          make O="$output_dir" \
                      sdm670-perf_defconfig \
          make -j $(nproc) \
                       O="$output_dir" \
                       CC=clang
          popd
          
      - name: Packaging the Kernel(LineageOS)
        run: |
          cp -v android_kernel_xiaomi_sdm710_LineageOS/out/arch/arm64/boot/Image.gz \
                     AnyKernel3/
          pushd AnyKernel3
          7z a -mx9 ../MI8SE_KernelSU_LineageOS.zip *
          popd
          
      - name: Creating Config Info
        run: |
          echo "Device: MI 8 SE
          Code: Sirius/Xmsirius
          Build Code: ${{ github.run_number }}
          KernelSU For MI8SE" >> INFO.txt
          
      - name: Uploading Kernel Package to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: MI8SE_KernelSU_LineageOS.zip
          name: "MI8SE_KernelSU"
          tag: " ${{ github.run_number }}_MI8SE_KernelSU"
          bodyFile: "INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
